export const PriceList = ['$', '$$', '$$$', '$$$$']

export const CategoriesList = ['Food',
  'Afghan',
  'African',
  'Arabian',
  'Armenian',
  'Australian',
  'Baguettes',
  'Belgian',
  'Bistros',
  'Brazilian',
  'breakfast_brunch',
  'British',
  'Burgers',
  'Cafes',
  'Caribbean',
  'Cheesesteaks',
  'Chinese',
  'Diners',
  'Dumplings',
  'Hotdogs',
  'Fondue',
  'Food Stands',
  'French',
  'German',
  'Greek',
  'Hot Pot',
  'Irish',
  'Italian',
  'Japanese',
  'Korean',
  'Latin',
  'Mediterranean',
  'Mexican',
  'Mongolian',
  'New Zealand',
  'Pakistani',
  'Pizza',
  'Polish',
  'Portuguese',
  'Pub Food',
  'Russian',
  'Scottish',
  'Seafood',
  'Southern',
  'Spanish',
  'Steak',
  'Thai']

export const HealthList = ['Vegan', 'Vegetarian']
